---

extends:
- stylelint-config-standard
- stylelint-config-rational-order

plugins:
- stylelint-order
- stylelint-config-rational-order/plugin

rules:
  indentation: 4
  declaration-empty-line-before: null
  plugin/rational-order:
  - true
  - border-in-box-model: true
    empty-line-between-groups: true
